# -*- coding: utf-8 -*-
"""travel_recommendation_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18a5fT_Kv7cl16s-VyxSKBQAs08z7Bn_Z
"""

# ══════════════════════════════════════════════════════════
#  SMART TRAVEL RECOMMENDER — ML Project
#  By: [Tumhara Naam] | BSc Honors AI/ML
#  Tools: K-Means Clustering + Cosine Similarity
#  Resume line: "Built AI Travel Recommender using
#               ML clustering — 30 destinations, 6 features"
# ══════════════════════════════════════════════════════════

# ┌─────────────────────────────────────────────┐
# │  CELL 1 — Libraries Import                  │
# │  (Ye pehle run karo — ek baar hi karna hai) │
# └─────────────────────────────────────────────┘

import numpy as np          # Numbers aur math
import pandas as pd         # Data table (DataFrame)
from sklearn.preprocessing import StandardScaler      # Normalize karna
from sklearn.cluster import KMeans                    # Clustering algorithm
from sklearn.metrics.pairwise import cosine_similarity # Similarity check
import matplotlib.pyplot as plt                       # Graphs banana
import warnings
warnings.filterwarnings('ignore')
np.random.seed(42)

print("Libraries load ho gayi!")


# ┌─────────────────────────────────────────────┐
# │  CELL 2 — Dataset Banana                   │
# │  30 destinations, 6 features               │
# └─────────────────────────────────────────────┘

# Yeh ek dictionary hai — jaise ek Excel table!
# Har key = ek column, Har value = us column ka data

destinations = {
    'City': [
        'Paris', 'Rome', 'Barcelona', 'Amsterdam', 'Prague',
        'Tokyo', 'Bangkok', 'Bali', 'Singapore', 'Dubai',
        'New York', 'Los Angeles', 'Miami', 'Chicago', 'Las Vegas',
        'Goa', 'Rajasthan', 'Kerala', 'Manali', 'Ladakh',
        'Munich', 'Berlin', 'Vienna', 'Zurich', 'Copenhagen',
        'Maldives', 'Santorini', 'Phuket', 'Cancun', 'Mauritius'
    ],
    'Country': [
        'France','Italy','Spain','Netherlands','Czech Republic',
        'Japan','Thailand','Indonesia','Singapore','UAE',
        'USA','USA','USA','USA','USA',
        'India','India','India','India','India',
        'Germany','Germany','Austria','Switzerland','Denmark',
        'Maldives','Greece','Thailand','Mexico','Mauritius'
    ],
    # Budget per day (USD) — kitna paisa lagega roz?
    'Budget_per_day_USD': [
        200, 150, 130, 180, 80,
        120,  60,  55, 160, 200,
        250, 200, 180, 170, 220,
         40,  35,  45,  30,  50,
        170, 140, 160, 280, 200,
        300, 250,  70, 110, 280
    ],
    # 1 = low, 5 = high — har feature score
    'Adventure_score': [
        3, 3, 4, 3, 3,
        4, 5, 5, 3, 4,
        3, 4, 4, 3, 5,
        5, 4, 5, 5, 5,
        3, 3, 2, 2, 3,
        4, 3, 5, 5, 4
    ],
    'Culture_score': [
        5, 5, 5, 4, 5,
        5, 4, 4, 3, 3,
        4, 3, 3, 4, 2,
        4, 5, 5, 3, 4,
        4, 4, 5, 4, 4,
        2, 4, 3, 3, 3
    ],
    'Beach_score': [
        1, 2, 3, 1, 1,
        1, 3, 5, 3, 3,
        2, 3, 5, 1, 1,
        5, 1, 4, 1, 1,
        1, 1, 1, 1, 1,
        5, 5, 5, 5, 5
    ],
    'Nightlife_score': [
        5, 4, 5, 4, 4,
        4, 5, 3, 5, 5,
        5, 5, 5, 4, 5,
        4, 2, 2, 2, 1,
        4, 5, 3, 3, 4,
        2, 3, 4, 4, 3
    ],
    'Safety_score': [
        4, 3, 3, 5, 4,
        5, 3, 4, 5, 5,
        3, 3, 3, 4, 4,
        4, 4, 5, 4, 4,
        5, 4, 5, 5, 5,
        5, 4, 3, 3, 4
    ],
    'Best_season': [
        'Spring','Spring','Summer','Summer','Spring',
        'Autumn','Winter','Summer','Winter','Winter',
        'Autumn','Spring','Winter','Summer','Spring',
        'Winter','Winter','Summer','Summer','Summer',
        'Summer','Summer','Spring','Summer','Summer',
        'Winter','Summer','Winter','Winter','Winter'
    ]
}

# Dictionary ko DataFrame mein convert karo
# DataFrame = ek table jaise Excel mein hoti hai
df = pd.DataFrame(destinations)

# Pehli 5 rows dekho
print("Dataset ready! Pehli 5 rows:")
print(df.head())
print(f"\nTotal destinations: {len(df)}")
print(f"Total features: {len(df.columns)}")


# ┌─────────────────────────────────────────────┐
# │  CELL 3 — Data Prepare Karo (ML ke liye)   │
# └─────────────────────────────────────────────┘

# Sirf numeric features lo — ML numbers samajhta hai!
features = [
    'Budget_per_day_USD',
    'Adventure_score',
    'Culture_score',
    'Beach_score',
    'Nightlife_score',
    'Safety_score'
]

# StandardScaler — sab features ko same scale pe laao
# Warna Budget(40-300) Adventure(1-5) se zyada dominate karega!
# Iske baad sab 0 ke aas paas hoga

scaler = StandardScaler()           # Scaler machine banao
X = df[features]                    # Sirf numeric columns lo
X_scaled = scaler.fit_transform(X)  # Scale karo!

print("Features select ki gayi:")
print(features)
print(f"\nOriginal budget range: {df['Budget_per_day_USD'].min()} - {df['Budget_per_day_USD'].max()}")
print(f"After scaling: {X_scaled[:,0].min():.2f} - {X_scaled[:,0].max():.2f}")
print("\nScaling complete!")


# ┌─────────────────────────────────────────────┐
# │  CELL 4 — K-Means Clustering               │
# │  Destinations ko groups mein baanto        │
# └─────────────────────────────────────────────┘

# K=5 matlab 5 types of travelers ke liye 5 groups
kmeans = KMeans(
    n_clusters=5,    # 5 groups chahiye
    random_state=42, # Reproducible results
    n_init=10        # 10 baar try karo, best lo
)

# fit_predict = train karo + label do ek saath!
df['Cluster'] = kmeans.fit_predict(X_scaled)

# Cluster numbers ko meaningful names do
cluster_names = {
    0: 'Budget Explorer',    # Kam budget, adventurous
    1: 'Luxury Traveler',    # High budget, comfort
    2: 'Beach & Party',      # Beach + nightlife lover
    3: 'Culture Seeker',     # History, art, food
    4: 'Adventure Junkie'    # Extreme adventures
}

df['Travel_Type'] = df['Cluster'].map(cluster_names)

print("Clustering complete! Har destination ka type:")
print(df[['City', 'Country', 'Budget_per_day_USD', 'Travel_Type']].to_string(index=False))


# ┌─────────────────────────────────────────────┐
# │  CELL 5 — Recommendation Function          │
# │  Tumhare liye best destinations dhundho    │
# └─────────────────────────────────────────────┘

def recommend_destinations(budget, adventure, culture,
                            beach, nightlife, safety, top_n=5):
    """
    Tumhara profile lo aur best destinations recommend karo!

    Parameters:
    -----------
    budget    : Roz kitna kharch kar sakte ho? (USD mein)
    adventure : Adventure kitna chahiye? (1=low, 5=high)
    culture   : Culture/history interest? (1=low, 5=high)
    beach     : Beach chahiye? (1=low, 5=high)
    nightlife : Nightlife chahiye? (1=low, 5=high)
    safety    : Safety priority? (1=low, 5=high)
    top_n     : Kitni recommendations chahiye?
    """

    # Step 1: Tumhara profile ek row mein
    user_profile = np.array([[budget, adventure, culture,
                               beach, nightlife, safety]])

    # Step 2: Same scaler se scale karo
    # (same scaler use karna ZAROORI hai!)
    user_scaled = scaler.transform(user_profile)

    # Step 3: Cosine Similarity
    # Tumhara profile vs har destination — kitna similar?
    # 1.0 = perfect match, 0.0 = bilkul alag
    similarities = cosine_similarity(user_scaled, X_scaled)[0]

    # Step 4: Similarity score add karo DataFrame mein
    df['Match_Score_%'] = (similarities * 100).round(1)

    # Step 5: Top N destinations sort karke do
    recommendations = df.nlargest(top_n, 'Match_Score_%')[
        ['City', 'Country', 'Budget_per_day_USD',
         'Travel_Type', 'Match_Score_%', 'Best_season']
    ].reset_index(drop=True)

    recommendations.index += 1  # 1 se start karo 0 se nahi
    return recommendations


print("Recommendation function ready hai!")
print("Ab CELL 6 run karo apna profile daalne ke liye!")


# ┌─────────────────────────────────────────────┐
# │  CELL 6 — APNA PROFILE DAALO!              │
# │  Yahan values change karo apne hisaab se   │
# └─────────────────────────────────────────────┘

print("=" * 55)
print("SMART TRAVEL RECOMMENDER")
print("=" * 55)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# YAHAN APNI VALUES DAALO — 1 se 5 tak
# (Budget USD mein daalo)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
MERA_BUDGET    = 200   # Roz kitna kharch kar sakte ho?
ADVENTURE      = 5     # Adventure kitna chahiye?
CULTURE        = 4     # Culture/history?
BEACH          = 3     # Beach?
NIGHTLIFE      = 2     # Nightlife?
SAFETY         = 5     # Safety priority?
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

print(f"\nTumhara Profile:")
print(f"  Budget/day : ${MERA_BUDGET}")
print(f"  Adventure  : {'★'*ADVENTURE}{'☆'*(5-ADVENTURE)}")
print(f"  Culture    : {'★'*CULTURE}{'☆'*(5-CULTURE)}")
print(f"  Beach      : {'★'*BEACH}{'☆'*(5-BEACH)}")
print(f"  Nightlife  : {'★'*NIGHTLIFE}{'☆'*(5-NIGHTLIFE)}")
print(f"  Safety     : {'★'*SAFETY}{'☆'*(5-SAFETY)}")

print("\nTop 5 Destinations for You:\n")
my_recs = recommend_destinations(
    MERA_BUDGET, ADVENTURE, CULTURE,
    BEACH, NIGHTLIFE, SAFETY, top_n=5
)
print(my_recs.to_string())


# ┌─────────────────────────────────────────────┐
# │  CELL 7 — Visualization                    │
# │  Beautiful graphs banana!                  │
# └─────────────────────────────────────────────┘

BG='#0d1117'; CARD='#161b22'
GOLD='#f0b429'; GRN='#3fb950'; BLU='#58a6ff'
RED='#f85149'; PUR='#bc8cff'; ORG='#ffa657'
MUT='#8b949e'; WHT='#e6edf3'
COLS = [GRN, GOLD, BLU, PUR, RED]

fig, axes = plt.subplots(1, 3, figsize=(18, 6), facecolor=BG)
fig.suptitle('Smart Travel Recommender — Results',
             fontsize=15, fontweight='bold', color=GOLD)

# Graph 1: Budget vs Adventure — clusters
ax1 = axes[0]
ax1.set_facecolor(CARD)
for c in range(5):
    mask = df['Cluster']==c
    ax1.scatter(df[mask]['Budget_per_day_USD'],
                df[mask]['Adventure_score'],
                c=COLS[c], s=100, edgecolors='white',
                lw=0.8, label=cluster_names[c], zorder=3)
    for _, row in df[mask].iterrows():
        ax1.annotate(row['City'],
                    (row['Budget_per_day_USD'], row['Adventure_score']),
                    fontsize=5.5, color=WHT, alpha=0.7,
                    xytext=(3,2), textcoords='offset points')
ax1.set_title('5 Traveler Types', color=GOLD, fontweight='bold')
ax1.set_xlabel('Budget/day (USD)', color=MUT)
ax1.set_ylabel('Adventure Score', color=MUT)
ax1.legend(fontsize=6.5, facecolor=BG, edgecolor=CARD, labelcolor=WHT)
ax1.grid(True, alpha=0.2); ax1.tick_params(colors=MUT)
for sp in ax1.spines.values(): sp.set_color(CARD)

# Graph 2: Your recommendations
ax2 = axes[1]
ax2.set_facecolor(CARD)
colors_bar = [GRN, GRN, GOLD, GOLD, BLU]
bars = ax2.barh(my_recs['City'], my_recs['Match_Score_%'],
                color=colors_bar, edgecolor='white', lw=0.5, alpha=0.85)
for bar, val in zip(bars, my_recs['Match_Score_%']):
    ax2.text(bar.get_width()+0.5, bar.get_y()+bar.get_height()/2,
             f'{val}%', va='center', fontsize=9, color=WHT, fontweight='bold')
ax2.set_title('Your Top Matches!', color=GRN, fontweight='bold')
ax2.set_xlabel('Match Score (%)', color=MUT)
ax2.grid(True, alpha=0.2, axis='x'); ax2.tick_params(colors=MUT)
for sp in ax2.spines.values(): sp.set_color(CARD)
ax2.set_xlim(0, 115)

# Graph 3: Radar chart — profile vs top match
ax3 = fig.add_subplot(1, 3, 3, projection='polar', facecolor=CARD)
categories = ['Budget', 'Adventure', 'Culture', 'Beach', 'Nightlife', 'Safety']
N = len(categories)
angles = [n/float(N)*2*np.pi for n in range(N)]
angles += angles[:1]

# Tumhara profile
user_vals = [1-MERA_BUDGET/300, ADVENTURE/5, CULTURE/5,
             BEACH/5, NIGHTLIFE/5, SAFETY/5]
user_vals += user_vals[:1]
ax3.plot(angles, user_vals, 'o-', lw=2, color=GRN, label='Tumhara Profile')
ax3.fill(angles, user_vals, alpha=0.15, color=GRN)

# Top match
top = df[df['City']==my_recs.iloc[0]['City']].iloc[0]
top_vals = [1-top['Budget_per_day_USD']/300,
            top['Adventure_score']/5,
            top['Culture_score']/5,
            top['Beach_score']/5,
            top['Nightlife_score']/5,
            top['Safety_score']/5]
top_vals += top_vals[:1]
ax3.plot(angles, top_vals, 'o-', lw=2, color=GOLD,
         label=f"Top: {my_recs.iloc[0]['City']}")
ax3.fill(angles, top_vals, alpha=0.1, color=GOLD)

ax3.set_xticks(angles[:-1])
ax3.set_xticklabels(categories, size=8.5, color=WHT)
ax3.set_facecolor(CARD); ax3.grid(color='#21262d', linewidth=0.8)
ax3.set_ylim(0, 1); ax3.tick_params(colors=MUT)
ax3.legend(loc='upper right', bbox_to_anchor=(1.35, 1.15),
           fontsize=8, facecolor=BG, edgecolor=CARD, labelcolor=WHT)
ax3.set_title('Profile Match', color=GOLD, fontweight='bold', pad=15)

plt.tight_layout()
plt.savefig('travel_recommender_result.png', dpi=150,
            bbox_inches='tight', facecolor=BG)
plt.show()
print("\nGraph save ho gaya: travel_recommender_result.png")


